export enum ActionType {
  LAST_ROW = "LAST_ROW",
  GET_LAST_DAY_DATA = "GET_LAST_DAY_DATA",
  GET_LAST_WEEK_DATA = "GET_LAST_WEEK_DATA",
  GET_LAST_MONTH_DATA = "GET_LAST_MONTH_DATA",
  GET_BAR_CHART_DATA = "GET_BAR_CHART_DATA",
  GET_PIE_CHART_DATA = "GET_PIE_CHART_DATA"
}
